version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install deps
          command: yarn install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: JASMINE_JUNIT_PATH=jasmine-junit.xml yarn test
      - store_test_results:
          path: jasmine-junit.xml

  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Lint code
          command: yarn lint

  commitlint:
    docker:
      - image: circleci/node:8
    branches:
      ignore:
        - master
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Lint commit messages
          command: git fetch --all && yarn commitlint:branch

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - commitlint:
          requires:
            - build
