version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Updating npm
          command: npmv=$(echo $(npm -v) | head -c 1); [ "$npmv" -lt "6" ] && sudo npm i -g npm
      - run:
          name: Install deps
          command: npm ci
      - save_cache:
          key: v2-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - /root/.npm

  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: JASMINE_JUNIT_PATH=jasmine-junit.xml npm test
      - store_test_results:
          path: jasmine-junit.xml

  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Lint code
          command: npm run lint

  commitlint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Lint commit messages
          command: git fetch --all && npm run commitlint:branch

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - commitlint:
          requires:
            - build
